version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app  # Mount current directory to /app in the container for live updates
    depends_on:
      - redis  # Ensure Redis is started before the app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"